name: Demo CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello From demo.yml"

      - name: Install
        env:
          ENV_VAL: Checking ENV
        run: echo "Printing ENV here -> $ENV_VAL"
