name: Demo CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello From demo.yml"

      - name: ENV
        env:
          ENV_VAL: Checking ENV
        run: echo "Printing ENV here -> $ENV_VAL"

      - name: Secrets
        env:
          App_ENV: Dev
          DB_password: ${{ secrets.DB_password }}
        run: echo "db password is $DB_password"
